export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#191c1d',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e1e3e4',
        'background': '#f8f9fa',
        'on-surface': '#191c1d',
        'surface-container-low': '#f3f4f5',
        'surface-bright': '#f8f9fa',
        'on-secondary-container': '#00743a',
        'tertiary': '#2e1900',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#2b1700',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#d5e3ff',
        'on-secondary-fixed-variant': '#005228',
        'on-primary': '#ffffff',
        'on-surface-variant': '#43474f',
        'primary-container': '#003366',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#663e00',
        'on-secondary': '#ffffff',
        'outline': '#737780',
        'surface-container-high': '#e7e8e9',
        'surface': '#f8f9fa',
        'on-primary-fixed-variant': '#1f477b',
        'on-primary-container': '#799dd6',
        'tertiary-fixed': '#ffddb9',
        'on-tertiary-container': '#d98a00',
        'secondary-fixed': '#6bfe9c',
        'tertiary-fixed-dim': '#ffb961',
        'primary': '#001e40',
        'tertiary-container': '#4b2c00',
        'inverse-primary': '#a7c8ff',
        'primary-fixed-dim': '#a7c8ff',
        'outline-variant': '#c3c6d1',
        'surface-dim': '#d9dadb',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-highest': '#e1e3e4',
        'on-primary-fixed': '#001b3c',
        'secondary': '#006d37',
        'secondary-fixed-dim': '#4ae183',
        'surface-container': '#edeeef',
        'on-secondary-fixed': '#00210c',
        'secondary-container': '#6bfe9c',
        'inverse-surface': '#2e3132',
        'surface-tint': '#3a5f94',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        'container-max': '1440px',
        lg: '24px',
        unit: '4px',
        gutter: '24px',
        md: '16px',
        xs: '4px',
        xl: '40px',
      },
      fontFamily: {
        'label-caps': ['Inter'],
        'body-sm': ['Inter'],
        'display-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'data-mono': ['Inter'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
    },
  },
}
